version: 0.1

services:
  - name: myreadify
    build:
      dockerfile: Dockerfile
    env:
      - MONGODB_URI=mongodb+srv://nazyalmeida:killmeleon@cluster4.vown5d8.mongodb.net/
    env_secrets:
      - MONGODB_URI
    port: